name: FoD SAST Scan and Import
#link de download da ferramenta FodUpload.jar:
#https://drive.google.com/drive/folders/1b5wkHwChO3PSjrRwQ1cvwj3I3UVXb_88?usp=sharing

on: workflow_dispatch

jobs:
  FoD-SAST-Scan:
    #Mudar para windows em caso de necessidade do msbuild 
    runs-on: ubuntu-latest

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        
      # Instala o java 8, necessário para executar a ferramenta de upload de código.
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Quando o scan concluir será gerado um arquivo SARIF output que traz as informações da análise para dentro do GitHub.
      - name: Download Results
        uses: fortify/gha-export-vulnerabilities@v1
        with:
          fod_base_url: https://ams.fortify.com
          fod_client_id: "cacb10a2-21b4-49bf-a8ea-f4f2d7aa72b2"
          fod_client_secret: "VVktNS5Sbm41V0Q3NlVrS2d5S2R6ZSp5VXhYMnlN0"
          fod_release_id: 305329
      
      # Import Fortify on Demand results to GitHub Security Code Scanning
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./gh-fortify-sast.sarif
